version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      db_nw:
  db:
    build: database
    image: postgres
    networks:
      db_nw:

networks:
  db_nw:
