FROM swift:4.0.3

RUN apt-get -qq update && apt-get -q -y install \ 
  postgresql postgresql-client postgresql-contrib libpq-dev cron


WORKDIR /app

COPY Package.swift ./
RUN swift package fetch

COPY Sources ./Sources
COPY Config ./Config
COPY Tests ./Tests

RUN swift build
RUN which cron

ADD refresh-cron /etc/cron.d/refresh-cron

RUN chmod 0644 /etc/cron.d/refresh-cron
RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log
