version: '3'
services:
  web:
    build: .
    ports:
      - "8121:8121"
    depends_on:
      - db
    networks:
      db_nw:
  test:
    build: .
    command: ["swift", "test"]
    ports:
      - "8121:8121"
    depends_on:
      - db
    networks:
      db_nw:

  db:
    build: database
    image: postgres
    ports:
      - "5432:5432"
    networks:
      db_nw:

networks:
  db_nw:

