version: '3'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      db_nw:
  db:
    build: database
    image: postgres
    ports:
      - "5432:5432"
    networks:
      db_nw:
  refresh:
    build:
      context: .
      dockerfile: Dockerfile-refresh
    depends_on:
      - db
    networks:
      db_nw:

networks:
  db_nw:
